### PR TITLE
Setting up LD_Library_Path + Creating necessary symbolic links

### PR DESCRIPTION
**Pull request by FranciscoThiesen**
These steps were needed to successfully run the example json_builder code (https://github.com/simdjson/experimental_json_builder/blob/main/src/toy_builder.cpp)

### CODE REVIEW

**Comment by lemire** [comment]
Let us get this sorted.

**Comment by lemire** [comment]
@FranciscoThiesen I verify your problem but I dislike the fix because I want the solution to run on any system and not be aarch64-specific. :-/

**Comment by lemire** [comment]
I am testing a fix that would be more elegant.

**Comment by lemire** [comment]
The following commit appears to suffice:

https://github.com/lemire/docker_programming_station/commit/87ba8252698112155f70b29ad3b7b761aa0706ba

Can you verify?

**Comment by lemire** [comment]
Sadly, it does not appear to work.

**Comment by lemire** [comment]
I am hopeful that the following commit will fix the issue in a portable manner:

https://github.com/lemire/docker_programming_station/commit/0ab94019848dc8e11e6ca2e6d3d11f97164f6491

Currently untested.

**Comment by lemire** [comment]
Tested. It works.

Change you check?

**Comment by FranciscoThiesen** [comment]
Let me take a look at your fix!

**Comment by FranciscoThiesen** [comment]
Your fix works for me too. Will close out this PR

**Pull request closed without merging**
